## conda environments names/ Singularity images pathes   
bakta_env: "snakemake-envs/bakta-1.8.2.yml"
prokka_env: "snakemake-envs/prokka-1.14.6.yml"
eggnog_env: "snakemake-envs/eggnog-2.1.12.yml"
emapper2gbk_env: "snakemake-envs/emapper2gbk-0.3.2.yml"
mpwt_image: ""
padmet_env: "snakemake-envs/padmet-5.0.3.yml"


## pathes to databases 
bak_db: ""
egg_db: ""
emapper2gbk_db: ""
metacyc_ref: ""

## pathes to files 
genomes_dir: ""
taxfile: ""
output_dir: "./"

## Eggnog option to put DB in memory : 
eggnog_db_optim: "" # needs a non-empty string ; if "yes", the DB will be copied in memory and used from there (faster but need more space in /dev/shm)
eggnog_db_optim_path: "" # if eggnog_db_optim is yes and you don't want the default path (need to start with /dev/shm)

## parameters
annotools: ["prokka", "bakta", "eggnog"]
to_remove: {
  "prokka" : [".err", ".faa", ".ffn", ".fna", ".fsa", ".gff", ".sqn", ".tbl", ".tsv", ".txt"],
  "bakta" : [".lisp", ".embl", ".ffn", ".fna", ".gff3", ".tsv", ".json", ".png", ".svg", ".txt", ".dat"]
  }

